version: '3.8'

services:

  postgres:
    image: postgres:15
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: bitnami/minio:latest
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - ./.env
    volumes:
      - minio_data:/data

  backend:
    build:
      context: ./admin/backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    depends_on:
      - postgres

  frontend:
    build:
      context: ./admin/frontend
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    depends_on:
      - backend

  mobile:
    build:
      context: ./mobile
      dockerfile: Dockerfile
    ports:
      - "8088:80"
    env_file:
      - ./.env

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend

volumes:
  pgdata:
  minio_data:
