version: '3.8'

services:
  # PostgreSQL Exporter для метрик
  postgres_exporter:
    image: prometheuscommunity/postgres-exporter:latest
    restart: unless-stopped
    environment:
      # Подставьте свои переменные из основного .env
      DATA_SOURCE_NAME: "postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/$POSTGRES_DB?sslmode=disable"
    ports:
      - "9187:9187"

  # Prometheus для сбора метрик
  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - postgres_exporter

  # Promtail для сбора логов
  promtail:
    image: grafana/promtail:3.0.0
    restart: unless-stopped
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./promtail-postgres.yaml:/etc/promtail/promtail.yaml:ro
    command: -config.file=/etc/promtail/promtail.yaml
    depends_on:
      - loki

  # Loki для хранения логов
  loki:
    image: grafana/loki:3.0.0
    restart: unless-stopped
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki_data:/loki
    ports:
      - "3100:3100"

  # Grafana для визуализации логов и метрик
  grafana:
    image: grafana/grafana:11.0.0
    restart: unless-stopped
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana"
    depends_on:
      - prometheus
      - loki

volumes:
  loki_data:
  grafana_data:
