name: gym_genius
description: "App for tracking workouts."
publish_to: 'none'
version: 0.1.12

environment:
  sdk: ^3.6.0

dependencies:
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  get_it: ^8.0.3
  http: ^1.4.0
  path: ^1.9.1
  sqflite: ^2.3.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  sqflite_common_ffi: ^2.3.5

flutter:
  uses-material-design: true
  assets:
    - lib/assets/exercise_pictures/
    - lib/assets/exercises.json
