name: Frontend CI/CD Pipeline

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        default: 'prod'

  push:
    branches:
      - main
    paths:
      - 'admin/frontend/**'

  pull_request:
    branches:
      - main
    paths:
      - 'admin/frontend/**'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: admin/frontend
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js and Cache Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'yarn'
          cache-dependency-path: admin/frontend/yarn.lock

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint code
        run: yarn lint

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: lint
    environment:
      name: prod
    steps:
      - name: Deploy over SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/gym-genius/admin/frontend/
            git pull
            cd ../backend/
            docker compose up -d --force-recreate --build frontend
