name: Mobile CI
on:
  push:
    branches: [ "main" ]
    paths:
      - 'mobile/**'        # run only if at least one file here changed
  # pull_request:
  #   branches: [ "main" ]
  #   paths:
  #     - 'mobile/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2

        with:
          channel: stable
          cache: true

      - name: Install Dependencies
        run: flutter pub get
        working-directory: mobile

      - name: Run Linter
        run: flutter analyze
        working-directory: mobile
